version: '2'
services:
  postgres:
    image: postgres:9.6
    environment: 
      POSTGRES_USER: cs
      POSTGRES_PASSWORD: <your password>
      POSTGRES_DB: crowdsource
    volumes:
    - ./db:/var/lib/postgresql/data
    - ./backups:/root/backups
  web:
    build: 
      dockerfile: ./docker/Dockerfile
      context: ./src/CrowdSource/publish
    depends_on:
    - postgres
    volumes:
    - ./segments:/app/wwwroot/segments:ro 
    ports:
    - 8081:5000
    links:
    - postgres:pg
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ConnectionStrings:DefaultConnection: "Server=pg;Port=5432;Database=crowdsource;User Id=cs;Password=<your password>;"
